### PR TITLE
Update Style.scc

### PR DESCRIPTION
**Pull request by MadinaSharapova97**

### CODE REVIEW

**Review by MadinaSharapova97 — COMMENTED** [review]
Edited style.css

**Comment by MadinaSharapova97** [comment]
Edited style.scc file

**Review by MadinaSharapova97 — COMMENTED** [review]
Ajoyib

**Comment by MadinaSharapova97** [comment]
asaasdkakflafkj

**Comment by MadinaSharapova97** [comment]
nbbbbbbbbbbbbbbb

**Comment by NuriyaSharopova** [comment]
Juda ajoyib

**Pull request merged**
